"""Mortal-style value-learning trainer for the V5 network.

This implements Mortal's reinforcement-learning algorithm (value-based,
*not* PPO) on top of this project's V5 components:

* The state is encoded by the unmodified ``EventStreamTransformer`` and a
  Douzero per-legal-action scorer **outputs ``Q(s, a)`` directly** (see
  :class:`~pymahjong.rl.v5.mortal_qnet.MortalQNet`).
* **Monte-Carlo Q target** per Mortal::

      q_target = gamma ** steps_to_done * kyoku_reward

  where ``steps_to_done`` is the number of the seat's *own* remaining
  decisions until the end of the kyoku and ``kyoku_reward`` is that
  kyoku's placement reward (see :mod:`pymahjong.rl.v5.grp`).
* **DQN loss** ``0.5 * MSE(q_taken, q_target)``.
* **CQL regulariser** (optional, Mortal's offline conservatism)
  ``min_q_weight * (logsumexp_a q - q_taken)``.
* **Auxiliary next-rank head** ``next_rank_weight * CE(aux_logits, final_rank)``.

Data is generated by **full-hanchan play** using
:class:`~pymahjong.rl.v4.hanchan_env.HanchanEnv`, which yields the
per-kyoku score sequence + final ranks needed for the reward.  By
**default** the 3 non-learner seats are a *frozen BC model* and only the
single (rotating) learner seat is trained: against this stationary
reference the points/placement reward is no longer zero-sum-symmetric, so
there is a real improvement gradient.  Set ``fixed_bc_opponents=False`` to
fall back to symmetric self-play with an
:class:`~pymahjong.rl.v4.opponent_pool.OpponentPool` of frozen historical
snapshots (the original behaviour, like the PPO path).

Unlike PPO, the update runs in ``train()`` mode (dropout on): the target
is a Monte-Carlo regression, not an importance-sampled ratio, so there is
no behaviour/target policy-consistency requirement.
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:
    import torch
    import torch.nn.functional as F
except Exception as e:  # noqa: BLE001
    raise RuntimeError("torch is required for Mortal-style V5 training") from e

from ..common.config import TransformerConfig
from ..v4.hanchan_env import HanchanEnv
from ..v4.opponent_pool import OpponentPool
from .grp import GRP, RewardCalculator
from .mortal_qnet import MortalQNet


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class MortalConfig:
    """Configuration for Mortal-style V5 value learning."""

    # -- schedule --
    total_steps: int = 1_000_000
    """Total *learner decisions* collected across the whole run."""
    rollout_steps: int = 8192
    """Learner decisions collected per optimisation round."""
    n_envs: int = 8
    n_epochs: int = 2
    batch_size: int = 256
    max_seq_len: int = 512

    # -- optimisation --
    gamma: float = 0.99
    lr: float = 1e-4
    grad_clip: float = 1.0
    weight_decay: float = 0.0
    huber_delta: float = 0.0
    """If ``>0`` use a Huber (smooth-L1) DQN loss with this ``beta`` instead
    of ``0.5*MSE``.  Huber caps the per-sample gradient at ``1`` once the
    error exceeds ``huber_delta``, so the huge initial TD error of a BC
    warm-start (``q~-20`` vs target ``~0``) no longer crushes the BC policy
    scale in the first update -- essential for the BC anchor to hold.  ``0``
    (default) keeps the original ``0.5*MSE``."""

    # -- Mortal loss weights --
    cql_enable: bool = False
    """Enable the CQL conservatism term.  Off by default for online
    self-play (matches Mortal's online mode); turn on for offline/static
    data to suppress OOD-action Q over-estimation."""
    min_q_weight: float = 1.0
    """Weight of the CQL term (only used when ``cql_enable``)."""
    next_rank_weight: float = 0.5
    """Weight of the auxiliary final-rank cross-entropy."""
    bc_anchor_weight: float = 0.0
    """Weight of the KL/CE-to-frozen-BC **policy anchor**.  ``>0`` adds a
    cross-entropy of the learner's Q-derived policy against the frozen BC
    policy (soft labels) -- i.e. forward ``KL(BC || learner)`` up to a
    constant -- which keeps the BC *action ordering* intact independently of
    the (collapsing) absolute Q scale.  This is the anti-collapse fix for BC
    warm-starts; CQL cannot do it because CQL anchors to the *current*
    behaviour, not BC.  ``0`` disables.  Needs a BC reference: the fixed-BC
    opponent is reused, else one is built from ``opponent_bc_checkpoint`` /
    the warm-started learner."""

    # -- reward shaping (GRP / placement) --
    reward_kind: str = "points"
    """``"points"`` (default, raw per-kyoku score delta in 25k units),
    ``"placement"`` (deterministic provisional placement, no extra net), or
    ``"grp"`` (needs a trained GRP checkpoint)."""
    grp_ckpt: Optional[str] = None
    """Path to a trained GRP checkpoint; required for ``reward_kind='grp'``."""
    grp_hidden: int = 64
    grp_layers: int = 2
    pts: Tuple[float, float, float, float] = (3.0, 1.0, -1.0, -3.0)
    reward_clip: float = 0.0
    """Symmetric clip on the per-decision Q-target (``<=0`` disables)."""

    # -- exploration during collection --
    epsilon: float = 0.0
    """Probability of a uniform random legal action during self-play
    collection.  ``0`` = pure greedy.  Small values (0.02-0.1) add
    exploration without a separate stochastic policy."""
    collect_stochastic: bool = False
    """If True, sample actions from a Boltzmann softmax over Q during
    collection instead of argmax (separate from ``epsilon``)."""

    # -- opponents: fixed frozen-BC environment (default) --
    fixed_bc_opponents: bool = True
    """If True (default), the 3 non-learner seats are a FROZEN BC model and
    only the single learner seat is trained.  The learner seat rotates
    ``0->1->2->3`` across hanchan for balanced seat / round-wind / dealer
    coverage.  Against a stationary BC reference the points/placement reward
    is no longer zero-sum-symmetric (the learner can out-earn the fixed BC),
    which gives a real improvement gradient -- unlike symmetric self-play,
    whose expected per-seat reward is ~0.  When False, fall back to the
    historical self-play opponent pool below."""
    opponent_bc_checkpoint: Optional[str] = None
    """BC checkpoint for the 3 frozen opponents in fixed-BC mode.  ``None``
    (default) reuses the learner's own warm-start ``bc_checkpoint``."""

    # -- self-play / opponent pool (only used when fixed_bc_opponents=False) --
    opponent_mix_ratio: float = 0.25
    n_frozen_seats: int = 1
    snapshot_interval: int = 50_000
    pool_capacity: int = 20
    pool_sampling: str = "pfsp"
    pfsp_p: float = 2.0

    # -- I/O --
    save_path: str = "checkpoints/mortal_v5.pt"
    """Path of the rolling "latest" checkpoint (overwritten each save)."""
    save_interval: int = 100_000
    """Save (and, if enabled, Mortal-eval) every this many learner steps."""
    keep_periodic: bool = True
    """If True, *also* persist a per-step copy ``<save_path stem>.step_<N>.pt``
    at every save so historical checkpoints are retained (not just the
    overwritten ``save_path``)."""
    snapshot_dir: Optional[str] = None

    # -- misc --
    device: Optional[str] = None
    seed: Optional[int] = None
    log_interval: int = 1

    # -- architecture (must match the BC ckpt) --
    scorer_hidden: int = 256
    action_proj_dim: Optional[int] = None

    # -- wandb (optional) --
    wandb_project: Optional[str] = None
    wandb_entity: Optional[str] = None
    wandb_name: Optional[str] = None
    wandb_tags: Optional[Tuple[str, ...]] = None
    wandb_mode: str = "online"

    # -- Mortal head-to-head eval on every checkpoint save (1v3 + 3v1) --
    # Disabled by default.  When enabled, after each checkpoint is written
    # the trainer exports a V5-compatible (DouzeroV5Transformer-layout)
    # checkpoint and runs ``mjai_bench_v2`` as a subprocess for two
    # matchups (1v3 and 3v1) vs the Mortal AI, logging ``mortal/*`` to
    # wandb.  All paths are server-specific and must be supplied.
    mortal_eval: bool = False
    """Enable Mortal head-to-head eval after each checkpoint save."""
    mortal_eval_hanchan: int = 1000
    """Hanchan per matchup.  More = lower variance but longer pause.
    1000 gives a very tight estimate (rank std-err ~0.035); with
    ``mortal_eval_workers`` 8 it finishes in a few tens of minutes.  For
    fast in-training periodic eval override this back to a small value
    (e.g. 16-64)."""
    mortal_eval_workers: int = 1
    """Concurrent bench processes per matchup (splits n_hanchan; the bench is
    latency-bound with low GPU util, so 4-8 ~ linear eval speedup)."""
    mortal_bench_script: Optional[str] = None
    """Absolute path to the ``mjai_bench_v2.py`` benchmark CLI."""
    mortal_bench_cwd: Optional[str] = None
    """Working directory for the bench subprocess (its src/ dir)."""
    mortal_ckpt: Optional[str] = None
    """Absolute path to the Mortal ``.pth`` weights (e.g. mortal_298k.pth)."""
    mortal_eval_python: Optional[str] = None
    """Interpreter for the eval subprocess.  ``None`` = ``sys.executable``."""
    mortal_eval_out_dir: Optional[str] = None
    """Root dir for per-step eval logs.  ``None`` = ``<save_path dir>/mortal_eval``."""
    mortal_eval_seed_start: int = 10000
    mortal_eval_seed_key: int = 4242
    mortal_eval_timeout_sec: float = 1800.0
    mortal_eval_amp: bool = False


# ---------------------------------------------------------------------------
# Sample container
# ---------------------------------------------------------------------------


@dataclass
class _Sample:
    obs: Dict[str, np.ndarray]
    action: int
    q_target: float
    rank: int


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------


class MortalTrainer:
    def __init__(
        self,
        config: Optional[MortalConfig] = None,
        transformer_config: Optional[TransformerConfig] = None,
        bc_checkpoint: Optional[str] = None,
    ):
        self.cfg = config or MortalConfig()
        self.tcfg = transformer_config or TransformerConfig()
        self._device = torch.device(
            self.cfg.device
            if self.cfg.device
            else ("cuda" if torch.cuda.is_available() else "cpu")
        )
        if self.cfg.seed is not None:
            torch.manual_seed(self.cfg.seed)
            np.random.seed(self.cfg.seed)

        self.model = MortalQNet(
            config=self.tcfg,
            scorer_hidden=self.cfg.scorer_hidden,
            action_proj_dim=self.cfg.action_proj_dim,
            aux_rank=True,
        ).to(self._device)

        self._bc_checkpoint = bc_checkpoint
        if bc_checkpoint and os.path.exists(bc_checkpoint):
            enc_missing, head_loaded = self.model.load_bc(bc_checkpoint, map_location=self._device)
            print(
                f"[mortal-v5] warm-started from {bc_checkpoint} "
                f"(encoder missing={len(enc_missing)}, "
                f"Q-head keys loaded={len(head_loaded)})",
                flush=True,
            )

        # Mortal-style optimiser: AdamW with weight decay applied ONLY to
        # Linear/Conv weights (not norms / biases / embeddings), betas
        # (0.9, 0.999), eps 1e-8 -- faithful to Mortal's train.py param
        # grouping.  When weight_decay == 0 (our historical default) both
        # groups decay to 0, so this is backward-compatible.
        params_dict: Dict[str, torch.Tensor] = {}
        to_decay: set = set()
        for mod_name, mod in self.model.named_modules():
            for name, param in mod.named_parameters(prefix=mod_name, recurse=False):
                params_dict[name] = param
                if isinstance(mod, (torch.nn.Linear, torch.nn.Conv1d)) and name.endswith("weight"):
                    to_decay.add(name)
        decay_params = [params_dict[n] for n in sorted(to_decay)]
        no_decay_params = [params_dict[n] for n in sorted(params_dict.keys() - to_decay)]
        self.optim = torch.optim.AdamW(
            [
                {"params": decay_params, "weight_decay": self.cfg.weight_decay},
                {"params": no_decay_params, "weight_decay": 0.0},
            ],
            lr=self.cfg.lr,
            betas=(0.9, 0.999),
            eps=1e-8,
        )

        # Reward calculator (+ optional GRP net).
        grp = None
        if self.cfg.reward_kind == "grp":
            grp = GRP(hidden_size=self.cfg.grp_hidden, num_layers=self.cfg.grp_layers)
            if self.cfg.grp_ckpt and os.path.exists(self.cfg.grp_ckpt):
                gck = torch.load(self.cfg.grp_ckpt, map_location="cpu")
                grp.load_state_dict(gck.get("model", gck))
                print(f"[mortal-v5] loaded GRP from {self.cfg.grp_ckpt}", flush=True)
            else:
                print(
                    "[mortal-v5] WARNING: reward_kind='grp' but no valid grp_ckpt; "
                    "using an UNTRAINED GRP (rewards will be near-meaningless). "
                    "Consider reward_kind='placement' instead.",
                    flush=True,
                )
        self.reward_calc = RewardCalculator(
            reward_kind=self.cfg.reward_kind,
            grp=grp,
            pts=self.cfg.pts,
            device="cpu",
        )

        self.pool = OpponentPool(
            capacity=self.cfg.pool_capacity,
            sampling=self.cfg.pool_sampling,
            pfsp_p=self.cfg.pfsp_p,
            seed=self.cfg.seed,
            save_dir=self.cfg.snapshot_dir,
        )
        self._opp_model: Optional[MortalQNet] = None  # lazily built frozen twin (pool mode)
        self._rng = np.random.default_rng(self.cfg.seed)
        self._total = 0
        self._last_snapshot = 0
        self._last_mortal_eval_step = -1
        # Fixed frozen-BC opponents (default): the 3 non-learner seats run a
        # frozen BC model so the learner trains against a stationary
        # reference; the learner seat rotates 0->1->2->3 across hanchan.
        self._bc_opponent: Optional[MortalQNet] = None
        self._learner_seat_cycle = 0
        if self.cfg.fixed_bc_opponents:
            self._bc_opponent = self._build_frozen_bc_opponent()
        # BC policy anchor (anti-collapse): a frozen BC reference the learner
        # policy is regularised toward.  Reuse the fixed-BC opponent when
        # present, else build one on demand.
        self._bc_anchor: Optional[MortalQNet] = None
        if self.cfg.bc_anchor_weight > 0:
            self._bc_anchor = self._bc_opponent or self._build_frozen_bc_opponent()
        self._wandb = self._maybe_init_wandb()

    # ------------------------------------------------------------------ frozen BC

    def _build_frozen_bc_opponent(self) -> MortalQNet:
        """Build the frozen BC model shared by the 3 opponent seats.

        If :attr:`MortalConfig.opponent_bc_checkpoint` is set it is loaded
        explicitly.  Otherwise the opponent is a **frozen clone of the
        just-warm-started learner** -- which, when the learner was
        warm-started from ``bc_checkpoint`` (and has not been trained yet),
        is exactly the BC model.  With no BC checkpoint at all the opponent
        is a frozen copy of the randomly-initialised learner (smoke-test
        fallback; a warning is printed).  The model is set to ``eval()`` and
        all parameters frozen -- it is never updated.
        """
        opp = MortalQNet(
            config=self.tcfg,
            scorer_hidden=self.cfg.scorer_hidden,
            action_proj_dim=self.cfg.action_proj_dim,
            aux_rank=True,
        ).to(self._device)
        ckpt = self.cfg.opponent_bc_checkpoint
        if ckpt and os.path.exists(ckpt):
            enc_missing, head_loaded = opp.load_bc(ckpt, map_location=self._device)
            src = (f"{ckpt} (encoder missing={len(enc_missing)}, "
                   f"Q-head keys loaded={len(head_loaded)})")
        else:
            # Clone the warm-started learner (== BC when bc_checkpoint was used).
            opp.load_state_dict(self.model.state_dict())
            if self._bc_checkpoint:
                src = f"frozen clone of learner warm-started from {self._bc_checkpoint}"
            else:
                print(
                    "[mortal-v5] WARNING: fixed_bc_opponents=True but no BC "
                    "checkpoint provided; the 3 opponents are a frozen copy of "
                    "the RANDOMLY-INITIALISED learner.  Pass --bc-checkpoint or "
                    "--opponent-bc-checkpoint for real BC opponents.",
                    flush=True,
                )
                src = "frozen clone of randomly-initialised learner (no BC ckpt)"
        opp.eval()
        for p in opp.parameters():
            p.requires_grad_(False)
        print(f"[mortal-v5] fixed BC opponents: {src}", flush=True)
        return opp

    # ------------------------------------------------------------------ wandb

    def _maybe_init_wandb(self):
        if not self.cfg.wandb_project:
            return None
        try:
            import wandb  # noqa: PLC0415
        except ImportError:
            print("[mortal-v5] wandb requested but not installed; skipping.", flush=True)
            return None
        run = wandb.init(
            project=self.cfg.wandb_project,
            entity=self.cfg.wandb_entity,
            name=self.cfg.wandb_name,
            tags=list(self.cfg.wandb_tags) if self.cfg.wandb_tags else None,
            mode=self.cfg.wandb_mode,
            config={k: getattr(self.cfg, k) for k in (
                "lr", "gamma", "rollout_steps", "batch_size", "n_epochs",
                "cql_enable", "min_q_weight", "next_rank_weight",
                "bc_anchor_weight",
                "reward_kind", "epsilon", "opponent_mix_ratio",
                "fixed_bc_opponents",
                "mortal_eval", "mortal_eval_hanchan",
            )},
        )
        return run

    def _wandb_log(self, data: dict) -> None:
        if self._wandb is not None:
            self._wandb.log({**data, "step": self._total})

    # ------------------------------------------------------------------ opponents

    def _opponent_twin(self) -> MortalQNet:
        if self._opp_model is None:
            self._opp_model = MortalQNet(
                config=self.tcfg,
                scorer_hidden=self.cfg.scorer_hidden,
                action_proj_dim=self.cfg.action_proj_dim,
                aux_rank=True,
            ).to(self._device)
            self._opp_model.eval()
        return self._opp_model

    def _assign_opponents(self, env_seed: int) -> Tuple[Dict[int, Any], set]:
        """Pick which seats use a frozen snapshot for this hanchan.

        Returns ``(seat -> snapshot_state_dict, opponent_seat_set)``.
        """
        if (
            self.pool.is_empty()
            or self.cfg.n_frozen_seats <= 0
            or self._rng.random() >= self.cfg.opponent_mix_ratio
        ):
            return {}, set()
        n = min(self.cfg.n_frozen_seats, 3)
        seats = list(self._rng.choice(4, size=n, replace=False))
        assignment: Dict[int, Any] = {}
        for s in seats:
            snap = self.pool.sample()
            if snap is not None:
                assignment[int(s)] = snap.state_dict
        return assignment, set(assignment.keys())

    def _assign_seats(self, env_seed: int) -> Tuple[Dict[int, Any], set, int]:
        """Decide seats for one hanchan in either opponent mode.

        Returns ``(opp_assign, opp_seats, learner_seat)``:

        * **fixed-BC mode**: one rotating learner seat (``0->1->2->3`` across
          successive hanchan) and the other 3 seats marked as opponents
          (all served by the shared frozen BC model, so ``opp_assign`` is
          empty); ``learner_seat`` is that seat.
        * **pool mode**: delegates to :meth:`_assign_opponents`; any
          non-opponent seat is a learner, so ``learner_seat`` is ``-1``.
        """
        if self.cfg.fixed_bc_opponents:
            ls = self._learner_seat_cycle % 4
            self._learner_seat_cycle += 1
            return {}, {s for s in range(4) if s != ls}, ls
        opp_assign, opp_seats = self._assign_opponents(env_seed)
        return opp_assign, opp_seats, -1

    # ------------------------------------------------------------------ acting

    @torch.no_grad()
    def _select_actions(
        self,
        model: MortalQNet,
        obs_list: List[Dict[str, np.ndarray]],
        stochastic: bool,
        epsilon: float,
    ) -> List[int]:
        """Batched Q action selection for a list of observations."""
        if not obs_list:
            return []
        feats, attn, amask = self._collate_obs(obs_list)
        actions = model.act_q(
            feats.to(self._device),
            attn.to(self._device),
            amask.to(self._device),
            epsilon=epsilon,
            deterministic=not stochastic,
        )
        return [int(a) for a in actions.cpu().numpy()]

    # ------------------------------------------------------------------ collection

    def _collect(self, n_steps: int) -> Tuple[List[_Sample], Dict[str, float]]:
        cfg = self.cfg
        self.model.eval()
        envs = [HanchanEnv() for _ in range(cfg.n_envs)]
        # Per-env mutable state.
        seeds = [int(self._rng.integers(0, 2**31 - 1)) for _ in range(cfg.n_envs)]
        for i, env in enumerate(envs):
            env.reset(seed=seeds[i])
        opp_assign: List[Dict[int, Any]] = [{} for _ in range(cfg.n_envs)]
        opp_seats: List[set] = [set() for _ in range(cfg.n_envs)]
        learner_seat: List[int] = [-1 for _ in range(cfg.n_envs)]
        # decisions[i] = list of dicts {kyoku, seat, obs, action}
        decisions: List[List[Dict[str, Any]]] = [[] for _ in range(cfg.n_envs)]
        kyoku_idx: List[int] = [0 for _ in range(cfg.n_envs)]
        for i in range(cfg.n_envs):
            opp_assign[i], opp_seats[i], learner_seat[i] = self._assign_seats(seeds[i])

        samples: List[_Sample] = []
        ranks_seen: List[int] = []
        hanchan_done = 0
        n_kyoku_total = 0

        def finalize_hanchan(i: int) -> None:
            nonlocal hanchan_done, n_kyoku_total
            env = envs[i]
            res = env.get_hanchan_result()
            n_kyoku_total += res.n_kyoku
            hanchan_done += 1
            rewards = self.reward_calc.kyoku_rewards(
                res.kyoku, res.ranks, res.final_scores
            )  # (T, 4)
            T = rewards.shape[0]
            # Group this env's learner decisions by (kyoku, seat) to assign
            # steps_to_done = (m-1-position) within each kyoku for that seat.
            groups: Dict[Tuple[int, int], List[Dict[str, Any]]] = {}
            for d in decisions[i]:
                if d["seat"] in opp_seats[i]:
                    continue  # opponent seats are not learner samples
                groups.setdefault((d["kyoku"], d["seat"]), []).append(d)
            for (k, seat), ds in groups.items():
                if k >= T:
                    # kyoku-index drift: a recorded decision references a
                    # kyoku beyond the reward table.  Should never happen;
                    # surface it loudly rather than silently dropping data.
                    print(
                        f"[mortal-v5] WARNING: decision kyoku {k} >= T={T} "
                        f"(seat {seat}); dropping {len(ds)} samples",
                        flush=True,
                    )
                    continue
                r = float(rewards[k, seat])
                rank = int(res.ranks[seat])
                m = len(ds)
                for pos, d in enumerate(ds):
                    steps_to_done = m - 1 - pos
                    q_t = (cfg.gamma ** steps_to_done) * r
                    if cfg.reward_clip and cfg.reward_clip > 0:
                        q_t = float(np.clip(q_t, -cfg.reward_clip, cfg.reward_clip))
                    samples.append(
                        _Sample(obs=d["obs"], action=d["action"], q_target=q_t, rank=rank)
                    )
                    ranks_seen.append(rank)
            # Reset env for a fresh hanchan.
            seeds[i] = int(self._rng.integers(0, 2**31 - 1))
            env.reset(seed=seeds[i])
            decisions[i] = []
            kyoku_idx[i] = 0
            opp_assign[i], opp_seats[i], learner_seat[i] = self._assign_seats(seeds[i])

        # Safety bound against a pathological env that never terminates.
        # Samples are only emitted when a hanchan finalizes, so the bound
        # must comfortably exceed the decision count of several full
        # hanchan (a hanchan is itself bounded by tobi / max_extra_kyoku).
        guard = 0
        guard_limit = 100 * (n_steps + cfg.n_envs * 5000)
        while len(samples) < n_steps:
            guard += 1
            if guard > guard_limit:
                print(
                    f"[mortal-v5] WARNING: collection guard tripped at "
                    f"{len(samples)}/{n_steps} samples; returning partial batch",
                    flush=True,
                )
                break
            # 1. Advance every env to a decision point (or finalize).
            ready_idx: List[int] = []
            ready_obs: List[Dict[str, np.ndarray]] = []
            ready_is_opp: List[bool] = []
            for i, env in enumerate(envs):
                if env.is_hanchan_over():
                    finalize_hanchan(i)
                # Move past completed kyoku.
                steps_guard = 0
                while (not env.is_hanchan_over()) and env.is_kyoku_over():
                    kyoku_idx[i] += 1
                    env.advance_to_next_kyoku()
                    steps_guard += 1
                    if steps_guard > 64:
                        break
                if env.is_hanchan_over():
                    finalize_hanchan(i)
                    continue
                obs = env.observe()
                ready_idx.append(i)
                ready_obs.append(obs)
                ready_is_opp.append(env.current_player in opp_seats[i])

            if not ready_idx:
                continue

            # 2. Select actions: the learner seat(s) batch through self.model;
            #    opponent seats batch through the frozen BC model (fixed-BC
            #    mode) or per-snapshot twins (pool mode).
            learner_pos = [k for k, o in enumerate(ready_is_opp) if not o]
            opp_pos = [k for k, o in enumerate(ready_is_opp) if o]

            actions_by_pos: Dict[int, int] = {}
            if learner_pos:
                la = self._select_actions(
                    self.model,
                    [ready_obs[k] for k in learner_pos],
                    stochastic=cfg.collect_stochastic,
                    epsilon=cfg.epsilon,
                )
                for k, a in zip(learner_pos, la):
                    actions_by_pos[k] = a
            if opp_pos and cfg.fixed_bc_opponents:
                # All 3 opponent seats share one frozen BC model -> one batch.
                oa = self._select_actions(
                    self._bc_opponent,
                    [ready_obs[k] for k in opp_pos],
                    stochastic=False,
                    epsilon=0.0,
                )
                for k, a in zip(opp_pos, oa):
                    actions_by_pos[k] = a
            else:
                for k in opp_pos:
                    i = ready_idx[k]
                    seat = envs[i].current_player
                    twin = self._opponent_twin()
                    # Snapshots are full MortalQNet state_dicts (keys prefixed
                    # ``encoder.`` / ``qhead.``); load into the full twin.
                    twin.load_state_dict(opp_assign[i][seat], strict=False)
                    a = self._select_actions(
                        twin, [ready_obs[k]], stochastic=False, epsilon=0.0
                    )[0]
                    actions_by_pos[k] = a

            # 3. Apply actions; record learner decisions.
            for k, i in enumerate(ready_idx):
                env = envs[i]
                seat = env.current_player
                action = actions_by_pos[k]
                is_opp = ready_is_opp[k]
                if not is_opp:
                    o = ready_obs[k]
                    decisions[i].append({
                        "kyoku": kyoku_idx[i],
                        "seat": seat,
                        "obs": {
                            "features": np.asarray(o["features"], dtype=np.bool_),
                            "attention_mask": np.asarray(o["attention_mask"], dtype=np.bool_),
                            "action_mask": np.asarray(o["action_mask"], dtype=np.bool_),
                        },
                        "action": int(action),
                    })
                env.kyoku_step(action)

        metrics = {
            "samples": float(len(samples)),
            "hanchan": float(hanchan_done),
            "kyoku": float(n_kyoku_total),
            "mean_rank": float(np.mean(ranks_seen) + 1.0) if ranks_seen else 0.0,
            "mean_q_target": float(np.mean([s.q_target for s in samples])) if samples else 0.0,
        }
        return samples, metrics

    # ------------------------------------------------------------------ collate

    def _collate_obs(self, obs_list: List[Dict[str, np.ndarray]]):
        seq_lens = [int(np.asarray(o["attention_mask"]).sum()) for o in obs_list]
        max_len = max(seq_lens) if seq_lens else 1
        event_dim = np.asarray(obs_list[0]["features"]).shape[-1]
        b = len(obs_list)
        features = torch.zeros(b, max_len, event_dim, dtype=torch.float32)
        attn = torch.zeros(b, max_len, dtype=torch.bool)
        amask = torch.zeros(b, np.asarray(obs_list[0]["action_mask"]).shape[0], dtype=torch.bool)
        for i, (o, slen) in enumerate(zip(obs_list, seq_lens)):
            feat_i = np.asarray(o["features"])[:slen]
            features[i, :slen] = torch.from_numpy(np.ascontiguousarray(feat_i)).float()
            attn[i, :slen] = True
            amask[i] = torch.from_numpy(
                np.ascontiguousarray(np.asarray(o["action_mask"], dtype=np.bool_))
            )
        return features, attn, amask

    # ------------------------------------------------------------------ update

    def _update(self, samples: List[_Sample]) -> Dict[str, float]:
        cfg = self.cfg
        if not samples:
            return {"dqn_loss": 0.0, "cql_loss": 0.0, "rank_loss": 0.0,
                    "anchor_loss": 0.0, "q_mean": 0.0}
        # Mortal trains in train() mode: the Q target is a Monte-Carlo
        # regression (no importance ratio), so dropout is harmless / acts
        # as a regulariser -- unlike the PPO path which must stay in eval().
        self.model.train()
        n = len(samples)
        acc = {"dqn_loss": 0.0, "cql_loss": 0.0, "rank_loss": 0.0,
               "anchor_loss": 0.0, "q_mean": 0.0}
        nb = 0
        for _ in range(cfg.n_epochs):
            order = np.random.permutation(n)
            for start in range(0, n, cfg.batch_size):
                mb = order[start : start + cfg.batch_size]
                if len(mb) == 0:
                    continue
                batch = [samples[j] for j in mb]
                feats, attn, amask = self._collate_obs([b.obs for b in batch])
                feats = feats.to(self._device)
                attn = attn.to(self._device)
                amask = amask.to(self._device)
                actions = torch.tensor([b.action for b in batch], dtype=torch.long, device=self._device)
                q_target = torch.tensor([b.q_target for b in batch], dtype=torch.float32, device=self._device)
                ranks = torch.tensor([b.rank for b in batch], dtype=torch.long, device=self._device)

                out = self.model.evaluate_q(feats, attn, amask, actions)
                q_taken = out["q_taken"]
                if cfg.huber_delta > 0:
                    dqn_loss = F.smooth_l1_loss(q_taken, q_target, beta=cfg.huber_delta)
                else:
                    dqn_loss = 0.5 * F.mse_loss(q_taken, q_target)
                cql_loss = q_taken.new_zeros(())
                if cfg.cql_enable:
                    cql_loss = (out["q_logsumexp"] - q_taken).mean()
                rank_loss = q_taken.new_zeros(())
                if out["aux_logits"] is not None:
                    rank_loss = F.cross_entropy(out["aux_logits"], ranks)

                # BC policy anchor: CE(learner policy, BC soft labels) over the
                # legal set == forward KL(BC || learner) up to a constant.
                # Preserves the BC action ordering regardless of Q scale.
                anchor_loss = q_taken.new_zeros(())
                if self._bc_anchor is not None:
                    with torch.no_grad():
                        _h, bc_qK, _pad, _li, _t = self._bc_anchor._q_legal(
                            feats, attn, amask, actions=None
                        )
                        bc_p = torch.softmax(bc_qK, dim=-1)
                    learner_logp = torch.log_softmax(out["q_K"], dim=-1)
                    ce = (bc_p * learner_logp).masked_fill(~out["action_pad_mask"], 0.0)
                    anchor_loss = -ce.sum(-1).mean()

                loss = (
                    dqn_loss
                    + (cfg.min_q_weight * cql_loss if cfg.cql_enable else 0.0)
                    + cfg.next_rank_weight * rank_loss
                    + (cfg.bc_anchor_weight * anchor_loss
                       if self._bc_anchor is not None else 0.0)
                )
                self.optim.zero_grad(set_to_none=True)
                loss.backward()
                if cfg.grad_clip > 0:
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), cfg.grad_clip)
                self.optim.step()

                acc["dqn_loss"] += float(dqn_loss.item())
                acc["cql_loss"] += float(cql_loss.item()) if cfg.cql_enable else 0.0
                acc["rank_loss"] += float(rank_loss.item())
                acc["anchor_loss"] += (
                    float(anchor_loss.item()) if self._bc_anchor is not None else 0.0
                )
                acc["q_mean"] += float(q_taken.mean().item())
                nb += 1
        if nb:
            for k in acc:
                acc[k] /= nb
        return acc

    # ------------------------------------------------------------------ save

    def _save(self) -> None:
        if not self.cfg.save_path:
            return
        os.makedirs(os.path.dirname(os.path.abspath(self.cfg.save_path)) or ".", exist_ok=True)
        payload = {
            "model": self.model.state_dict(),
            "encoder": self.model.encoder.state_dict(),
            "qhead": self.model.qhead.state_dict(),
            "step": self._total,
            "config": self.cfg.__dict__,
            "transformer_config": self.tcfg.__dict__,
        }
        # Atomic write of the rolling "latest" checkpoint.
        tmp = self.cfg.save_path + ".tmp"
        torch.save(payload, tmp)
        os.replace(tmp, self.cfg.save_path)
        # Optionally also keep a per-step historical copy.
        if self.cfg.keep_periodic:
            stem, ext = os.path.splitext(self.cfg.save_path)
            periodic = f"{stem}.step_{self._total:09d}{ext or '.pt'}"
            try:
                # Hardlink is instant + zero extra disk; fall back to copy
                # across filesystems.
                if os.path.exists(periodic):
                    os.remove(periodic)
                os.link(self.cfg.save_path, periodic)
            except OSError:
                import shutil
                shutil.copy2(self.cfg.save_path, periodic)

    def _export_v5_ckpt(self, path: str) -> None:
        """Write a DouzeroV5Transformer-layout checkpoint for the mjai bench.

        The Mortal bench harness (``mjai_bench_v2``) loads our agent via
        ``--v5-ckpt`` as a :class:`DouzeroV5Transformer`.  ``MortalQNet``'s
        encoder + Douzero Q-head share that exact weight layout (the scorer
        outputs a per-action scalar; greedy argmax over Q equals argmax over
        the V5 policy logits), so we remap our state_dict into the V5 key
        namespace: encoder keys are top-level, Q-head keys (``action_proj``
        / ``scorer``) lose their ``qhead.`` prefix, and the unused
        ``policy_head`` is omitted (V5 derives logits from the scorer)."""
        v5_sd: Dict[str, torch.Tensor] = {}
        for k, v in self.model.encoder.state_dict().items():
            # The encoder is a full EventStreamTransformer and carries an
            # unused ``policy_head`` (V5 derives logits from the scorer and
            # has no policy_head), so drop it to keep the export key set an
            # exact match for DouzeroV5Transformer.
            if k.startswith("policy_head"):
                continue
            v5_sd[k] = v
        for k, v in self.model.qhead.state_dict().items():
            if k.startswith("aux_rank_head") or k == "default_action_descriptors":
                continue  # not part of DouzeroV5Transformer
            v5_sd[k] = v  # action_proj.* / scorer.*
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        tmp = path + ".tmp"
        torch.save(
            {"model": v5_sd, "step": self._total, "transformer_config": self.tcfg.__dict__},
            tmp,
        )
        os.replace(tmp, path)

    def _run_mortal_eval(self) -> None:
        """Run 1v3 / 3v1 head-to-head vs Mortal on the current weights and
        log the results to wandb.  Never raises -- a failed eval logs
        ``mortal/<matchup>/failed=1`` and training continues unharmed."""
        cfg = self.cfg
        if not cfg.mortal_eval:
            return
        step = int(self._total)
        if step == self._last_mortal_eval_step:
            return
        missing = [n for n, v in (("mortal_bench_script", cfg.mortal_bench_script),
                                  ("mortal_bench_cwd", cfg.mortal_bench_cwd),
                                  ("mortal_ckpt", cfg.mortal_ckpt)) if not v]
        if missing:
            print(f"[mortal-eval] disabled: missing config {missing}", flush=True)
            return
        try:
            from ..v4.mortal_eval import run_mortal_matchups
        except Exception as e:  # noqa: BLE001
            print(f"[mortal-eval] import failed: {e!r}", flush=True)
            return

        base = os.path.dirname(os.path.abspath(cfg.save_path or "checkpoints/mortal_v5.pt")) or "."
        frozen = os.path.join(base, f"_mortal_eval_v5_step_{step}.pt")
        try:
            self._export_v5_ckpt(frozen)
        except Exception as e:  # noqa: BLE001
            print(f"[mortal-eval] step={step} V5 export failed: {e!r}", flush=True)
            return

        out_root = cfg.mortal_eval_out_dir or os.path.join(base, "mortal_eval")
        out_dir = os.path.join(out_root, f"step_{step}")

        try:
            if self._device.type == "cuda":
                torch.cuda.empty_cache()
        except Exception:  # noqa: BLE001
            pass

        print(f"[mortal-eval] step={step} running 1v3/3v1 "
              f"({cfg.mortal_eval_hanchan} hanchan each)...", flush=True)
        was_training = self.model.training
        t0 = time.time()
        try:
            metrics = run_mortal_matchups(
                frozen,
                bench_script=cfg.mortal_bench_script,
                bench_cwd=cfg.mortal_bench_cwd,
                mortal_ckpt=cfg.mortal_ckpt,
                out_dir=out_dir,
                n_hanchan=cfg.mortal_eval_hanchan,
                d_model=self.tcfg.d_model,
                n_heads=self.tcfg.n_heads,
                n_layers=self.tcfg.n_layers,
                ff_mult=self.tcfg.ff_mult,
                scorer_hidden=cfg.scorer_hidden,
                eval_python=cfg.mortal_eval_python,
                seed_start=cfg.mortal_eval_seed_start,
                seed_key=cfg.mortal_eval_seed_key,
                device="cuda" if self._device.type == "cuda" else "cpu",
                amp=cfg.mortal_eval_amp,
                timeout_sec=cfg.mortal_eval_timeout_sec,
                n_workers=cfg.mortal_eval_workers,
            )
            self._last_mortal_eval_step = step
            r13 = metrics.get("mortal/1v3/v5_avg_rank")
            r31 = metrics.get("mortal/3v1/v5_avg_rank")
            print(
                f"[mortal-eval] step={step} done in {time.time()-t0:.0f}s  "
                f"1v3 v5_avg_rank={r13 if r13 is None else round(r13,3)}  "
                f"3v1 v5_avg_rank={r31 if r31 is None else round(r31,3)}",
                flush=True,
            )
            self._wandb_log(metrics)
        except Exception as e:  # noqa: BLE001
            print(f"[mortal-eval] step={step} failed: {e!r}", flush=True)
        finally:
            if was_training:
                self.model.train()
            try:
                if os.path.exists(frozen):
                    os.remove(frozen)
            except Exception:  # noqa: BLE001
                pass

    # ------------------------------------------------------------------ loop

    def train(self) -> MortalQNet:
        cfg = self.cfg
        update_count = 0
        # Step-0 baseline eval: capture warm-started (BC) performance vs.
        # Mortal BEFORE any gradient update, so a later regression can be
        # attributed to training drift rather than a flawed starting
        # point or a broken eval pipeline.  ``_last_mortal_eval_step``
        # starts at -1, so this never gets de-duplicated against a later
        # save-interval-triggered eval at the same step.
        if cfg.mortal_eval:
            print(f"[mortal-v5] step={self._total} running step-0 baseline eval...", flush=True)
            self._run_mortal_eval()
        while self._total < cfg.total_steps:
            t0 = time.time()
            samples, cmetrics = self._collect(cfg.rollout_steps)
            self._total += len(samples)
            t1 = time.time()
            umetrics = self._update(samples)
            t2 = time.time()
            update_count += 1

            # Snapshot for the self-play opponent pool (pool mode only; the
            # fixed-BC environment never updates, so no snapshots are needed).
            if (
                not cfg.fixed_bc_opponents
                and self._total - self._last_snapshot >= cfg.snapshot_interval
            ):
                self.pool.add_snapshot(self.model, step=self._total)
                self._last_snapshot = self._total

            if update_count % cfg.log_interval == 0:
                print(
                    f"[mortal-v5] step={self._total} "
                    f"dqn={umetrics['dqn_loss']:.4f} "
                    f"cql={umetrics['cql_loss']:.4f} "
                    f"rank={umetrics['rank_loss']:.4f} "
                    f"anchor={umetrics['anchor_loss']:.4f} "
                    f"q={umetrics['q_mean']:.3f} "
                    f"mean_rank={cmetrics['mean_rank']:.3f} "
                    f"hanchan={int(cmetrics['hanchan'])} "
                    f"collect={t1-t0:.1f}s update={t2-t1:.1f}s",
                    flush=True,
                )
            self._wandb_log({
                "train/dqn_loss": umetrics["dqn_loss"],
                "train/cql_loss": umetrics["cql_loss"],
                "train/rank_loss": umetrics["rank_loss"],
                "train/anchor_loss": umetrics["anchor_loss"],
                "train/q_mean": umetrics["q_mean"],
                "collect/mean_rank": cmetrics["mean_rank"],
                "collect/hanchan": cmetrics["hanchan"],
                "collect/mean_q_target": cmetrics["mean_q_target"],
            })

            if self._total % cfg.save_interval < cfg.rollout_steps:
                self._save()
                self._run_mortal_eval()

        self._save()
        self._run_mortal_eval()
        if self._wandb is not None:
            self._wandb.finish()
        return self.model


def train_mortal_v5(
    bc_checkpoint: Optional[str] = None,
    config: Optional[MortalConfig] = None,
    transformer_config: Optional[TransformerConfig] = None,
) -> MortalQNet:
    """Entry point: train a V5 network with Mortal's value-learning algorithm."""
    trainer = MortalTrainer(
        config=config,
        transformer_config=transformer_config,
        bc_checkpoint=bc_checkpoint,
    )
    return trainer.train()


__all__ = ["MortalConfig", "MortalTrainer", "train_mortal_v5"]
