language: cpp
os: linux
dist: focal
addons:
  apt:
    packages: &common_packages
      - python3.9-dev
      - clang
      - cmake

# command to install dependencies
install:
  - sudo python3.9 setup.py install
# command to run tests
script: 
  - python -c "import pymahjong;pymahjong.test()"