language: generic
os: linux
dist: focal

git:
  depth: false

addons:
  apt:
    packages: &common_packages  
      - clang
      - cmake

before_install: 
  - python 

# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: 
  - python -c "import pymahjong;pymahjong.test()"