language: cpp
os: linux
dist: bionic
addons:
  apt:
    packages: &common_packages
      - clang
      - python3.9-dev

# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: 
  - python -c "import pymahjong;pymahjong.test()"