language: generic
os: linux
dist: focal

git:
  depth: false

addons:
  apt:
    packages: &common_packages  
      - clang
      - cmake

before_install: 
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sudo chmod +x miniconda.sh && ./miniconda.sh -b -p ~/anaconda3 
  - ~/anaconda3/bin/conda init && source ~/.bashrc

# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: 
  - python -c "import pymahjong;pymahjong.test()"