language: python
os: linux
dist: focal

git:
  depth: false
  
python:
  - "3.9"

addons:
  apt:
    packages: &common_packages  
      - clang
      - cmake

# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: 
  - python -c "import pymahjong;pymahjong.test()"