language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  
before_install: 
  - sudo apt update
  - sudo apt install -y clang cmake

# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: python ./pymahjong/test.py