"""Mortal-style value-learning trainer for the Douzero network.

This implements Mortal's reinforcement-learning algorithm (value-based,
*not* PPO) on top of this project's Douzero components:

* The state is encoded by the unmodified ``EventStreamTransformer`` and a
  Douzero per-legal-action scorer **outputs ``Q(s, a)`` directly** (see
  :class:`~pymahjong.rl.mortal_qnet.MortalQNet`).
* **Monte-Carlo Q target** per Mortal::

      q_target = gamma ** steps_to_done * kyoku_reward

  where ``steps_to_done`` is the number of the seat's *own* remaining
  decisions until the end of the kyoku and ``kyoku_reward`` is that
  kyoku's placement reward (see :mod:`pymahjong.rl.grp`).
* **DQN loss** ``0.5 * MSE(q_taken, q_target)``.
* **CQL regulariser** (optional, Mortal's offline conservatism)
  ``min_q_weight * (logsumexp_a q - q_taken)``.
* **Auxiliary next-rank head** ``next_rank_weight * CE(aux_logits, final_rank)``.

Data is generated by **self-play over full hanchan** using
:class:`~pymahjong.rl.hanchan_env.HanchanEnv`, which yields the
per-kyoku score sequence + final ranks needed for the placement reward.
An :class:`~pymahjong.rl.opponent_pool.OpponentPool` injects frozen
historical snapshots for diversity, exactly like the PPO path.

Unlike PPO, the update runs in ``train()`` mode (dropout on): the target
is a Monte-Carlo regression, not an importance-sampled ratio, so there is
no behaviour/target policy-consistency requirement.
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:
    import torch
    import torch.nn.functional as F
except Exception as e:  # noqa: BLE001
    raise RuntimeError("torch is required for Mortal-style training") from e

from .common.config import TransformerConfig
from .hanchan_env import HanchanEnv
from .opponent_pool import OpponentPool
from .grp import GRP, RewardCalculator
from .mortal_qnet import MortalQNet


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class MortalConfig:
    """Configuration for Mortal-style value learning."""

    # -- schedule --
    total_steps: int = 1_000_000
    """Total *learner decisions* collected across the whole run."""
    rollout_steps: int = 8192
    """Learner decisions collected per optimisation round."""
    n_envs: int = 8
    n_epochs: int = 2
    batch_size: int = 256
    max_seq_len: int = 512

    # -- optimisation --
    gamma: float = 0.99
    lr: float = 1e-4
    grad_clip: float = 1.0
    weight_decay: float = 0.0

    # -- Mortal loss weights --
    cql_enable: bool = False
    """Enable the CQL conservatism term.  Off by default for online
    self-play (matches Mortal's online mode); turn on for offline/static
    data to suppress OOD-action Q over-estimation."""
    min_q_weight: float = 1.0
    """Weight of the CQL term (only used when ``cql_enable``)."""
    next_rank_weight: float = 0.5
    """Weight of the auxiliary final-rank cross-entropy."""

    # -- reward shaping (GRP / placement) --
    reward_kind: str = "placement"
    """``"placement"`` (default, no extra net), ``"grp"`` (needs a trained
    GRP checkpoint), or ``"points"`` (raw score delta)."""
    grp_ckpt: Optional[str] = None
    """Path to a trained GRP checkpoint; required for ``reward_kind='grp'``."""
    grp_hidden: int = 64
    grp_layers: int = 2
    pts: Tuple[float, float, float, float] = (3.0, 1.0, -1.0, -3.0)
    reward_clip: float = 0.0
    """Symmetric clip on the per-decision Q-target (``<=0`` disables)."""

    # -- exploration during collection --
    epsilon: float = 0.0
    """Probability of a uniform random legal action during self-play
    collection.  ``0`` = pure greedy.  Small values (0.02-0.1) add
    exploration without a separate stochastic policy."""
    collect_stochastic: bool = False
    """If True, sample actions from a Boltzmann softmax over Q during
    collection instead of argmax (separate from ``epsilon``)."""

    # -- self-play / opponent pool --
    opponent_mix_ratio: float = 0.25
    n_frozen_seats: int = 1
    snapshot_interval: int = 50_000
    pool_capacity: int = 20
    pool_sampling: str = "pfsp"
    pfsp_p: float = 2.0

    # -- I/O --
    save_path: str = "checkpoints/mortal_v5.pt"
    """Path of the rolling "latest" checkpoint (overwritten each save)."""
    save_interval: int = 100_000
    """Save (and, if enabled, Mortal-eval) every this many learner steps."""
    keep_periodic: bool = True
    """If True, *also* persist a per-step copy ``<save_path stem>.step_<N>.pt``
    at every save so historical checkpoints are retained (not just the
    overwritten ``save_path``)."""
    snapshot_dir: Optional[str] = None

    # -- misc --
    device: Optional[str] = None
    seed: Optional[int] = None
    log_interval: int = 1

    # -- architecture (must match the BC ckpt) --
    scorer_hidden: int = 256
    action_proj_dim: Optional[int] = None

    # -- wandb (optional) --
    wandb_project: Optional[str] = None
    wandb_entity: Optional[str] = None
    wandb_name: Optional[str] = None
    wandb_tags: Optional[Tuple[str, ...]] = None
    wandb_mode: str = "online"

    # -- Mortal head-to-head eval on every checkpoint save (1v3 + 3v1) --
    # Disabled by default.  When enabled, after each checkpoint is written
    # the trainer exports a Douzero-compatible (DouzeroTransformer-layout)
    # checkpoint and runs ``mjai_bench_v2`` as a subprocess for two
    # matchups (1v3 and 3v1) vs the Mortal AI, logging ``mortal/*`` to
    # wandb.  All paths are server-specific and must be supplied.
    mortal_eval: bool = False
    """Enable Mortal head-to-head eval after each checkpoint save."""
    mortal_eval_hanchan: int = 16
    """Hanchan per matchup.  More = lower variance but longer pause."""
    mortal_bench_script: Optional[str] = None
    """Absolute path to the ``mjai_bench_v2.py`` benchmark CLI."""
    mortal_bench_cwd: Optional[str] = None
    """Working directory for the bench subprocess (its src/ dir)."""
    mortal_ckpt: Optional[str] = None
    """Absolute path to the Mortal ``.pth`` weights (e.g. mortal_298k.pth)."""
    mortal_eval_python: Optional[str] = None
    """Interpreter for the eval subprocess.  ``None`` = ``sys.executable``."""
    mortal_eval_out_dir: Optional[str] = None
    """Root dir for per-step eval logs.  ``None`` = ``<save_path dir>/mortal_eval``."""
    mortal_eval_seed_start: int = 10000
    mortal_eval_seed_key: int = 4242
    mortal_eval_timeout_sec: float = 1800.0
    mortal_eval_amp: bool = False


# ---------------------------------------------------------------------------
# Sample container
# ---------------------------------------------------------------------------


@dataclass
class _Sample:
    obs: Dict[str, np.ndarray]
    action: int
    q_target: float
    rank: int


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------


class MortalTrainer:
    def __init__(
        self,
        config: Optional[MortalConfig] = None,
        transformer_config: Optional[TransformerConfig] = None,
        bc_checkpoint: Optional[str] = None,
    ):
        self.cfg = config or MortalConfig()
        self.tcfg = transformer_config or TransformerConfig()
        self._device = torch.device(
            self.cfg.device
            if self.cfg.device
            else ("cuda" if torch.cuda.is_available() else "cpu")
        )
        if self.cfg.seed is not None:
            torch.manual_seed(self.cfg.seed)
            np.random.seed(self.cfg.seed)

        self.model = MortalQNet(
            config=self.tcfg,
            scorer_hidden=self.cfg.scorer_hidden,
            action_proj_dim=self.cfg.action_proj_dim,
            aux_rank=True,
        ).to(self._device)

        if bc_checkpoint and os.path.exists(bc_checkpoint):
            enc_missing, head_loaded = self.model.load_bc(bc_checkpoint, map_location=self._device)
            print(
                f"[mortal-v5] warm-started from {bc_checkpoint} "
                f"(encoder missing={len(enc_missing)}, "
                f"Q-head keys loaded={len(head_loaded)})",
                flush=True,
            )

        self.optim = torch.optim.AdamW(
            self.model.parameters(), lr=self.cfg.lr, weight_decay=self.cfg.weight_decay
        )

        # Reward calculator (+ optional GRP net).
        grp = None
        if self.cfg.reward_kind == "grp":
            grp = GRP(hidden_size=self.cfg.grp_hidden, num_layers=self.cfg.grp_layers)
            if self.cfg.grp_ckpt and os.path.exists(self.cfg.grp_ckpt):
                gck = torch.load(self.cfg.grp_ckpt, map_location="cpu")
                grp.load_state_dict(gck.get("model", gck))
                print(f"[mortal-v5] loaded GRP from {self.cfg.grp_ckpt}", flush=True)
            else:
                print(
                    "[mortal-v5] WARNING: reward_kind='grp' but no valid grp_ckpt; "
                    "using an UNTRAINED GRP (rewards will be near-meaningless). "
                    "Consider reward_kind='placement' instead.",
                    flush=True,
                )
        self.reward_calc = RewardCalculator(
            reward_kind=self.cfg.reward_kind,
            grp=grp,
            pts=self.cfg.pts,
            device="cpu",
        )

        self.pool = OpponentPool(
            capacity=self.cfg.pool_capacity,
            sampling=self.cfg.pool_sampling,
            pfsp_p=self.cfg.pfsp_p,
            seed=self.cfg.seed,
            save_dir=self.cfg.snapshot_dir,
        )
        self._opp_model: Optional[MortalQNet] = None  # lazily built frozen twin
        self._rng = np.random.default_rng(self.cfg.seed)
        self._total = 0
        self._last_snapshot = 0
        self._last_mortal_eval_step = -1
        self._wandb = self._maybe_init_wandb()

    # ------------------------------------------------------------------ wandb

    def _maybe_init_wandb(self):
        if not self.cfg.wandb_project:
            return None
        try:
            import wandb  # noqa: PLC0415
        except ImportError:
            print("[mortal-v5] wandb requested but not installed; skipping.", flush=True)
            return None
        run = wandb.init(
            project=self.cfg.wandb_project,
            entity=self.cfg.wandb_entity,
            name=self.cfg.wandb_name,
            tags=list(self.cfg.wandb_tags) if self.cfg.wandb_tags else None,
            mode=self.cfg.wandb_mode,
            config={k: getattr(self.cfg, k) for k in (
                "lr", "gamma", "rollout_steps", "batch_size", "n_epochs",
                "cql_enable", "min_q_weight", "next_rank_weight",
                "reward_kind", "epsilon", "opponent_mix_ratio",
                "mortal_eval", "mortal_eval_hanchan",
            )},
        )
        return run

    def _wandb_log(self, data: dict) -> None:
        if self._wandb is not None:
            self._wandb.log({**data, "step": self._total})

    # ------------------------------------------------------------------ opponents

    def _opponent_twin(self) -> MortalQNet:
        if self._opp_model is None:
            self._opp_model = MortalQNet(
                config=self.tcfg,
                scorer_hidden=self.cfg.scorer_hidden,
                action_proj_dim=self.cfg.action_proj_dim,
                aux_rank=True,
            ).to(self._device)
            self._opp_model.eval()
        return self._opp_model

    def _assign_opponents(self, env_seed: int) -> Tuple[Dict[int, Any], set]:
        """Pick which seats use a frozen snapshot for this hanchan.

        Returns ``(seat -> snapshot_state_dict, opponent_seat_set)``.
        """
        if (
            self.pool.is_empty()
            or self.cfg.n_frozen_seats <= 0
            or self._rng.random() >= self.cfg.opponent_mix_ratio
        ):
            return {}, set()
        n = min(self.cfg.n_frozen_seats, 3)
        seats = list(self._rng.choice(4, size=n, replace=False))
        assignment: Dict[int, Any] = {}
        for s in seats:
            snap = self.pool.sample()
            if snap is not None:
                assignment[int(s)] = snap.state_dict
        return assignment, set(assignment.keys())

    # ------------------------------------------------------------------ acting

    @torch.no_grad()
    def _select_actions(
        self,
        model: MortalQNet,
        obs_list: List[Dict[str, np.ndarray]],
        stochastic: bool,
        epsilon: float,
    ) -> List[int]:
        """Batched Q action selection for a list of observations."""
        if not obs_list:
            return []
        feats, attn, amask = self._collate_obs(obs_list)
        actions = model.act_q(
            feats.to(self._device),
            attn.to(self._device),
            amask.to(self._device),
            epsilon=epsilon,
            deterministic=not stochastic,
        )
        return [int(a) for a in actions.cpu().numpy()]

    # ------------------------------------------------------------------ collection

    def _collect(self, n_steps: int) -> Tuple[List[_Sample], Dict[str, float]]:
        cfg = self.cfg
        self.model.eval()
        envs = [HanchanEnv() for _ in range(cfg.n_envs)]
        # Per-env mutable state.
        seeds = [int(self._rng.integers(0, 2**31 - 1)) for _ in range(cfg.n_envs)]
        for i, env in enumerate(envs):
            env.reset(seed=seeds[i])
        opp_assign: List[Dict[int, Any]] = [{} for _ in range(cfg.n_envs)]
        opp_seats: List[set] = [set() for _ in range(cfg.n_envs)]
        # decisions[i] = list of dicts {kyoku, seat, obs, action}
        decisions: List[List[Dict[str, Any]]] = [[] for _ in range(cfg.n_envs)]
        kyoku_idx: List[int] = [0 for _ in range(cfg.n_envs)]
        for i in range(cfg.n_envs):
            opp_assign[i], opp_seats[i] = self._assign_opponents(seeds[i])

        samples: List[_Sample] = []
        ranks_seen: List[int] = []
        hanchan_done = 0
        n_kyoku_total = 0

        def finalize_hanchan(i: int) -> None:
            nonlocal hanchan_done, n_kyoku_total
            env = envs[i]
            res = env.get_hanchan_result()
            n_kyoku_total += res.n_kyoku
            hanchan_done += 1
            rewards = self.reward_calc.kyoku_rewards(
                res.kyoku, res.ranks, res.final_scores
            )  # (T, 4)
            T = rewards.shape[0]
            # Group this env's learner decisions by (kyoku, seat) to assign
            # steps_to_done = (m-1-position) within each kyoku for that seat.
            groups: Dict[Tuple[int, int], List[Dict[str, Any]]] = {}
            for d in decisions[i]:
                if d["seat"] in opp_seats[i]:
                    continue  # opponent seats are not learner samples
                groups.setdefault((d["kyoku"], d["seat"]), []).append(d)
            for (k, seat), ds in groups.items():
                if k >= T:
                    # kyoku-index drift: a recorded decision references a
                    # kyoku beyond the reward table.  Should never happen;
                    # surface it loudly rather than silently dropping data.
                    print(
                        f"[mortal-v5] WARNING: decision kyoku {k} >= T={T} "
                        f"(seat {seat}); dropping {len(ds)} samples",
                        flush=True,
                    )
                    continue
                r = float(rewards[k, seat])
                rank = int(res.ranks[seat])
                m = len(ds)
                for pos, d in enumerate(ds):
                    steps_to_done = m - 1 - pos
                    q_t = (cfg.gamma ** steps_to_done) * r
                    if cfg.reward_clip and cfg.reward_clip > 0:
                        q_t = float(np.clip(q_t, -cfg.reward_clip, cfg.reward_clip))
                    samples.append(
                        _Sample(obs=d["obs"], action=d["action"], q_target=q_t, rank=rank)
                    )
                    ranks_seen.append(rank)
            # Reset env for a fresh hanchan.
            seeds[i] = int(self._rng.integers(0, 2**31 - 1))
            env.reset(seed=seeds[i])
            decisions[i] = []
            kyoku_idx[i] = 0
            opp_assign[i], opp_seats[i] = self._assign_opponents(seeds[i])

        # Safety bound against a pathological env that never terminates.
        # Samples are only emitted when a hanchan finalizes, so the bound
        # must comfortably exceed the decision count of several full
        # hanchan (a hanchan is itself bounded by tobi / max_extra_kyoku).
        guard = 0
        guard_limit = 100 * (n_steps + cfg.n_envs * 5000)
        while len(samples) < n_steps:
            guard += 1
            if guard > guard_limit:
                print(
                    f"[mortal-v5] WARNING: collection guard tripped at "
                    f"{len(samples)}/{n_steps} samples; returning partial batch",
                    flush=True,
                )
                break
            # 1. Advance every env to a decision point (or finalize).
            ready_idx: List[int] = []
            ready_obs: List[Dict[str, np.ndarray]] = []
            ready_is_opp: List[bool] = []
            for i, env in enumerate(envs):
                if env.is_hanchan_over():
                    finalize_hanchan(i)
                # Move past completed kyoku.
                steps_guard = 0
                while (not env.is_hanchan_over()) and env.is_kyoku_over():
                    kyoku_idx[i] += 1
                    env.advance_to_next_kyoku()
                    steps_guard += 1
                    if steps_guard > 64:
                        break
                if env.is_hanchan_over():
                    finalize_hanchan(i)
                    continue
                obs = env.observe()
                ready_idx.append(i)
                ready_obs.append(obs)
                ready_is_opp.append(env.current_player in opp_seats[i])

            if not ready_idx:
                continue

            # 2. Select actions: learner seats batched through self.model,
            #    opponent seats batched through the frozen twin per snapshot.
            learner_pos = [k for k, o in enumerate(ready_is_opp) if not o]
            opp_pos = [k for k, o in enumerate(ready_is_opp) if o]

            actions_by_pos: Dict[int, int] = {}
            if learner_pos:
                la = self._select_actions(
                    self.model,
                    [ready_obs[k] for k in learner_pos],
                    stochastic=cfg.collect_stochastic,
                    epsilon=cfg.epsilon,
                )
                for k, a in zip(learner_pos, la):
                    actions_by_pos[k] = a
            for k in opp_pos:
                i = ready_idx[k]
                seat = envs[i].current_player
                twin = self._opponent_twin()
                # Snapshots are full MortalQNet state_dicts (keys prefixed
                # ``encoder.`` / ``qhead.``); load into the full twin.
                twin.load_state_dict(opp_assign[i][seat], strict=False)
                a = self._select_actions(
                    twin, [ready_obs[k]], stochastic=False, epsilon=0.0
                )[0]
                actions_by_pos[k] = a

            # 3. Apply actions; record learner decisions.
            for k, i in enumerate(ready_idx):
                env = envs[i]
                seat = env.current_player
                action = actions_by_pos[k]
                is_opp = ready_is_opp[k]
                if not is_opp:
                    o = ready_obs[k]
                    decisions[i].append({
                        "kyoku": kyoku_idx[i],
                        "seat": seat,
                        "obs": {
                            "features": np.asarray(o["features"], dtype=np.bool_),
                            "attention_mask": np.asarray(o["attention_mask"], dtype=np.bool_),
                            "action_mask": np.asarray(o["action_mask"], dtype=np.bool_),
                        },
                        "action": int(action),
                    })
                env.kyoku_step(action)

        metrics = {
            "samples": float(len(samples)),
            "hanchan": float(hanchan_done),
            "kyoku": float(n_kyoku_total),
            "mean_rank": float(np.mean(ranks_seen) + 1.0) if ranks_seen else 0.0,
            "mean_q_target": float(np.mean([s.q_target for s in samples])) if samples else 0.0,
        }
        return samples, metrics

    # ------------------------------------------------------------------ collate

    def _collate_obs(self, obs_list: List[Dict[str, np.ndarray]]):
        seq_lens = [int(np.asarray(o["attention_mask"]).sum()) for o in obs_list]
        max_len = max(seq_lens) if seq_lens else 1
        event_dim = np.asarray(obs_list[0]["features"]).shape[-1]
        b = len(obs_list)
        features = torch.zeros(b, max_len, event_dim, dtype=torch.float32)
        attn = torch.zeros(b, max_len, dtype=torch.bool)
        amask = torch.zeros(b, np.asarray(obs_list[0]["action_mask"]).shape[0], dtype=torch.bool)
        for i, (o, slen) in enumerate(zip(obs_list, seq_lens)):
            feat_i = np.asarray(o["features"])[:slen]
            features[i, :slen] = torch.from_numpy(np.ascontiguousarray(feat_i)).float()
            attn[i, :slen] = True
            amask[i] = torch.from_numpy(
                np.ascontiguousarray(np.asarray(o["action_mask"], dtype=np.bool_))
            )
        return features, attn, amask

    # ------------------------------------------------------------------ update

    def _update(self, samples: List[_Sample]) -> Dict[str, float]:
        cfg = self.cfg
        if not samples:
            return {"dqn_loss": 0.0, "cql_loss": 0.0, "rank_loss": 0.0, "q_mean": 0.0}
        # Mortal trains in train() mode: the Q target is a Monte-Carlo
        # regression (no importance ratio), so dropout is harmless / acts
        # as a regulariser -- unlike the PPO path which must stay in eval().
        self.model.train()
        n = len(samples)
        acc = {"dqn_loss": 0.0, "cql_loss": 0.0, "rank_loss": 0.0, "q_mean": 0.0}
        nb = 0
        for _ in range(cfg.n_epochs):
            order = np.random.permutation(n)
            for start in range(0, n, cfg.batch_size):
                mb = order[start : start + cfg.batch_size]
                if len(mb) == 0:
                    continue
                batch = [samples[j] for j in mb]
                feats, attn, amask = self._collate_obs([b.obs for b in batch])
                feats = feats.to(self._device)
                attn = attn.to(self._device)
                amask = amask.to(self._device)
                actions = torch.tensor([b.action for b in batch], dtype=torch.long, device=self._device)
                q_target = torch.tensor([b.q_target for b in batch], dtype=torch.float32, device=self._device)
                ranks = torch.tensor([b.rank for b in batch], dtype=torch.long, device=self._device)

                out = self.model.evaluate_q(feats, attn, amask, actions)
                q_taken = out["q_taken"]
                dqn_loss = 0.5 * F.mse_loss(q_taken, q_target)
                cql_loss = q_taken.new_zeros(())
                if cfg.cql_enable:
                    cql_loss = (out["q_logsumexp"] - q_taken).mean()
                rank_loss = q_taken.new_zeros(())
                if out["aux_logits"] is not None:
                    rank_loss = F.cross_entropy(out["aux_logits"], ranks)

                loss = (
                    dqn_loss
                    + (cfg.min_q_weight * cql_loss if cfg.cql_enable else 0.0)
                    + cfg.next_rank_weight * rank_loss
                )
                self.optim.zero_grad(set_to_none=True)
                loss.backward()
                if cfg.grad_clip > 0:
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), cfg.grad_clip)
                self.optim.step()

                acc["dqn_loss"] += float(dqn_loss.item())
                acc["cql_loss"] += float(cql_loss.item()) if cfg.cql_enable else 0.0
                acc["rank_loss"] += float(rank_loss.item())
                acc["q_mean"] += float(q_taken.mean().item())
                nb += 1
        if nb:
            for k in acc:
                acc[k] /= nb
        return acc

    # ------------------------------------------------------------------ save

    def _save(self) -> None:
        if not self.cfg.save_path:
            return
        os.makedirs(os.path.dirname(os.path.abspath(self.cfg.save_path)) or ".", exist_ok=True)
        payload = {
            "model": self.model.state_dict(),
            "encoder": self.model.encoder.state_dict(),
            "qhead": self.model.qhead.state_dict(),
            "step": self._total,
            "config": self.cfg.__dict__,
            "transformer_config": self.tcfg.__dict__,
        }
        # Atomic write of the rolling "latest" checkpoint.
        tmp = self.cfg.save_path + ".tmp"
        torch.save(payload, tmp)
        os.replace(tmp, self.cfg.save_path)
        # Optionally also keep a per-step historical copy.
        if self.cfg.keep_periodic:
            stem, ext = os.path.splitext(self.cfg.save_path)
            periodic = f"{stem}.step_{self._total:09d}{ext or '.pt'}"
            try:
                # Hardlink is instant + zero extra disk; fall back to copy
                # across filesystems.
                if os.path.exists(periodic):
                    os.remove(periodic)
                os.link(self.cfg.save_path, periodic)
            except OSError:
                import shutil
                shutil.copy2(self.cfg.save_path, periodic)

    def _export_v5_ckpt(self, path: str) -> None:
        """Write a DouzeroTransformer-layout checkpoint for the mjai bench.

        The Mortal bench harness (``mjai_bench_v2``) loads our agent via
        ``--v5-ckpt`` as a :class:`DouzeroTransformer`.  ``MortalQNet``'s
        encoder + Douzero Q-head share that exact weight layout (the scorer
        outputs a per-action scalar; greedy argmax over Q equals argmax over
        the Douzero policy logits), so we remap our state_dict into the Douzero key
        namespace: encoder keys are top-level, Q-head keys (``action_proj``
        / ``scorer``) lose their ``qhead.`` prefix, and the unused
        ``policy_head`` is omitted (the Douzero head derives logits from the scorer)."""
        v5_sd: Dict[str, torch.Tensor] = {}
        for k, v in self.model.encoder.state_dict().items():
            # The encoder is a full EventStreamTransformer and carries an
            # unused ``policy_head`` (the Douzero head derives logits from the scorer and
            # has no policy_head), so drop it to keep the export key set an
            # exact match for DouzeroTransformer.
            if k.startswith("policy_head"):
                continue
            v5_sd[k] = v
        for k, v in self.model.qhead.state_dict().items():
            if k.startswith("aux_rank_head") or k == "default_action_descriptors":
                continue  # not part of DouzeroTransformer
            v5_sd[k] = v  # action_proj.* / scorer.*
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        tmp = path + ".tmp"
        torch.save(
            {"model": v5_sd, "step": self._total, "transformer_config": self.tcfg.__dict__},
            tmp,
        )
        os.replace(tmp, path)

    def _run_mortal_eval(self) -> None:
        """Run 1v3 / 3v1 head-to-head vs Mortal on the current weights and
        log the results to wandb.  Never raises -- a failed eval logs
        ``mortal/<matchup>/failed=1`` and training continues unharmed."""
        cfg = self.cfg
        if not cfg.mortal_eval:
            return
        step = int(self._total)
        if step == self._last_mortal_eval_step:
            return
        missing = [n for n, v in (("mortal_bench_script", cfg.mortal_bench_script),
                                  ("mortal_bench_cwd", cfg.mortal_bench_cwd),
                                  ("mortal_ckpt", cfg.mortal_ckpt)) if not v]
        if missing:
            print(f"[mortal-eval] disabled: missing config {missing}", flush=True)
            return
        try:
            from .mortal_eval import run_mortal_matchups
        except Exception as e:  # noqa: BLE001
            print(f"[mortal-eval] import failed: {e!r}", flush=True)
            return

        base = os.path.dirname(os.path.abspath(cfg.save_path or "checkpoints/mortal_v5.pt")) or "."
        frozen = os.path.join(base, f"_mortal_eval_v5_step_{step}.pt")
        try:
            self._export_v5_ckpt(frozen)
        except Exception as e:  # noqa: BLE001
            print(f"[mortal-eval] step={step} Douzero export failed: {e!r}", flush=True)
            return

        out_root = cfg.mortal_eval_out_dir or os.path.join(base, "mortal_eval")
        out_dir = os.path.join(out_root, f"step_{step}")

        try:
            if self._device.type == "cuda":
                torch.cuda.empty_cache()
        except Exception:  # noqa: BLE001
            pass

        print(f"[mortal-eval] step={step} running 1v3/3v1 "
              f"({cfg.mortal_eval_hanchan} hanchan each)...", flush=True)
        was_training = self.model.training
        t0 = time.time()
        try:
            metrics = run_mortal_matchups(
                frozen,
                bench_script=cfg.mortal_bench_script,
                bench_cwd=cfg.mortal_bench_cwd,
                mortal_ckpt=cfg.mortal_ckpt,
                out_dir=out_dir,
                n_hanchan=cfg.mortal_eval_hanchan,
                d_model=self.tcfg.d_model,
                n_heads=self.tcfg.n_heads,
                n_layers=self.tcfg.n_layers,
                ff_mult=self.tcfg.ff_mult,
                scorer_hidden=cfg.scorer_hidden,
                eval_python=cfg.mortal_eval_python,
                seed_start=cfg.mortal_eval_seed_start,
                seed_key=cfg.mortal_eval_seed_key,
                device="cuda" if self._device.type == "cuda" else "cpu",
                amp=cfg.mortal_eval_amp,
                timeout_sec=cfg.mortal_eval_timeout_sec,
            )
            self._last_mortal_eval_step = step
            r13 = metrics.get("mortal/1v3/v5_avg_rank")
            r31 = metrics.get("mortal/3v1/v5_avg_rank")
            print(
                f"[mortal-eval] step={step} done in {time.time()-t0:.0f}s  "
                f"1v3 v5_avg_rank={r13 if r13 is None else round(r13,3)}  "
                f"3v1 v5_avg_rank={r31 if r31 is None else round(r31,3)}",
                flush=True,
            )
            self._wandb_log(metrics)
        except Exception as e:  # noqa: BLE001
            print(f"[mortal-eval] step={step} failed: {e!r}", flush=True)
        finally:
            if was_training:
                self.model.train()
            try:
                if os.path.exists(frozen):
                    os.remove(frozen)
            except Exception:  # noqa: BLE001
                pass

    # ------------------------------------------------------------------ loop

    def train(self) -> MortalQNet:
        cfg = self.cfg
        update_count = 0
        while self._total < cfg.total_steps:
            t0 = time.time()
            samples, cmetrics = self._collect(cfg.rollout_steps)
            self._total += len(samples)
            t1 = time.time()
            umetrics = self._update(samples)
            t2 = time.time()
            update_count += 1

            # Snapshot for the opponent pool.
            if self._total - self._last_snapshot >= cfg.snapshot_interval:
                self.pool.add_snapshot(self.model, step=self._total)
                self._last_snapshot = self._total

            if update_count % cfg.log_interval == 0:
                print(
                    f"[mortal-v5] step={self._total} "
                    f"dqn={umetrics['dqn_loss']:.4f} "
                    f"cql={umetrics['cql_loss']:.4f} "
                    f"rank={umetrics['rank_loss']:.4f} "
                    f"q={umetrics['q_mean']:.3f} "
                    f"mean_rank={cmetrics['mean_rank']:.3f} "
                    f"hanchan={int(cmetrics['hanchan'])} "
                    f"collect={t1-t0:.1f}s update={t2-t1:.1f}s",
                    flush=True,
                )
            self._wandb_log({
                "train/dqn_loss": umetrics["dqn_loss"],
                "train/cql_loss": umetrics["cql_loss"],
                "train/rank_loss": umetrics["rank_loss"],
                "train/q_mean": umetrics["q_mean"],
                "collect/mean_rank": cmetrics["mean_rank"],
                "collect/hanchan": cmetrics["hanchan"],
                "collect/mean_q_target": cmetrics["mean_q_target"],
            })

            if self._total % cfg.save_interval < cfg.rollout_steps:
                self._save()
                self._run_mortal_eval()

        self._save()
        self._run_mortal_eval()
        if self._wandb is not None:
            self._wandb.finish()
        return self.model


def train_mortal(
    bc_checkpoint: Optional[str] = None,
    config: Optional[MortalConfig] = None,
    transformer_config: Optional[TransformerConfig] = None,
) -> MortalQNet:
    """Entry point: train a Douzero network with Mortal's value-learning algorithm."""
    trainer = MortalTrainer(
        config=config,
        transformer_config=transformer_config,
        bc_checkpoint=bc_checkpoint,
    )
    return trainer.train()


__all__ = ["MortalConfig", "MortalTrainer", "train_mortal"]
